## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking  memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Thu Oct 01 12:27:10 IST 2020
org.gradle.daemon=true
kotlin.code.style=official
org.gradle.parallel=true
# android.enableR8.libraries=true
org.gradle.caching=false
org.gradle.jvmargs=-Xmx6144M -Dkotlin.daemon.jvm.options\="-Xmx6144M"
android.useAndroidX=true
kapt.include.compile.classpath=false
android.enableJetifier=true
kapt.use.worker.api=true
kapt.incremental.apt=true
#org.gradle.configureondemand=true
#----------GradlePluginVersion-----------------
androidgradlev=8.5.2
ktlintgradlev=10.1.0
detektv=1.18.0-RC2
gradleversionpluginv=0.49.0
kotlin=1.9.23
coroutinesandroid=1.3.2
ktlint=1.2.1
safeargsv=2.7.7
googleservicev=4.4.2
fabricv=1.31.2
dynatracev=8.+
sonarv=2.7
sceneformv=1.15.0
crashlyticsv=2.8.1
parcelizev=1.6.20-RC2
#----------GradlePluginId-----------------
detekt=io.gitlab.arturbosch.detekt
ktlintgradle=org.jlleitschuh.gradle.ktlint
androidapplication=com.android.application
androiddynamicfeature=com.android.dynamic-feature
androidlibrary=com.android.library
kotlinjvm=org.jetbrains.kotlin.jvm
kotlinandroid=org.jetbrains.kotlin.android
kotlinandroidextensions=org.jetbrains.kotlin.android.extensions
gradleversionplugin=com.github.ben-manes.versions
safeargs=androidx.navigation.safeargs.kotlin
kapt=org.jetbrains.kotlin.kapt
fabric=io.fabric
crashlytics=com.google.firebase.crashlytics
sonar=org.sonarqube
parcelize=org.jetbrains.kotlin.plugin.parcelize
dynatrace=com.dynatrace.instrumentation
googleservice=com.google.gms.google-services
arsceneform=com.google.ar.sceneform.plugin
#----------GradleOldWayPlugins-----------------
androidgradle=com.android.tools.build:gradle:8.5.2
kotlingradle=org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.23
safeargsold=androidx.navigation:navigation-safe-args-gradle-plugin:2.7.7
googleserviceold=com.google.gms:google-services:4.4.2
fabricold=io.fabric.tools:gradle:1.31.2
crashlyticsold=com.google.firebase:firebase-crashlytics-gradle:2.9.4
dynatraceold=com.dynatrace.tools.android:gradle-plugin:8.+
sonarold=org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.7
sceneform=com.google.ar.sceneform:plugin:1.15.0

#DB Encryption
artifactory_user=app-user
artifactory_password=cmVmdGtuOjAxOjE3NDQyODkzODY6TlJ0R2lsQjZoMm1mdmJvVVB5RGdqV05uU09I
artifactory_context_url=https://digitalartifacts.olamnet.com/artifactory/
artifactory_dev_repo_key=libs-release
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
