package com.olam.warehouse.presentation.enums

/**
 * Created by Baskaran Kannan on 12/25/2019.
 */

enum class UserRoles(val role: String) {
    BASE("BASE"),
    SUPPLIER("ROLE_RECEIVING"),
    OFFLOADING("ROLE_OFFLOADING"),
    MTNR("ROLE_STO_RECEIVING"),
    GRN("ROLE_PROCUREMENT"),
    QUALITY("ROLE_QUALITY"),
    QUALITYAPPROVAL("ROLE_QUALITY_APPROVAL"),
    APPROVE("ROLE_BRANCH_CONTROLLER"),
    MTNT("ROLE_DISPATCH_STO"),
    SALES("ROLE_DISPATCH_SALES"),
    EXPORTSALES("ROLE_DISPATCH_EXPORT_SALES"),
    PROCESSING("ROLE_PROCESSING"),
    GATEENTRY("ROLE_GATE_ENTRY"),
    GATEENTRYAPPROVAL("ROLE_GATE_ENTRY_APPROVER"),
    SAMPLEID("ROLE_SAMPLE"),
    INVENTORY("ROLE_INVENTORY"),
    TRANSACTIONDETAILS("ROLE_TRANS_DETAILS"),
    REPRINT("ROLE_REPRINT"),
    ADVANCING("ROLE_ADVANCING"),
    SCAN("ROLE_TAP_TO_SCAN"),
    SWEEPINGS("ROLE_SWEEPINGS"),
    PPQ("ROLE_PPQ"),
    LOTQUALITY("ROLE_LOT_QUALITY"),
    CONTAINER("ROLE_CONTAINER"),
    THIRDPARTY("ROLE_THIRDPARTY_SALES"),
    THIRDPARTY_OWNERSHIP("ROLE_THIRDPARTY_OWNERSHIP"),
    THIRDPARTY_TP_OLAM("ROLE_THIRDPARTY_TO_OLAM"),
    THIRDPARTY_TP_TO_TP("ROLE_THIRDPARTY_TO_THIRDPARTY"),
    PCH("ROLE_PCH"),
    PILE("ROLE_PILE_MANAGEMENT"),
    INVOICE("ROLE_INVOICE"),
    VIRTUAL_MTNT("ROLE_VIRTUAL_MTNT"),
    VIRTUAL_MTNR("ROLE_VIRTUAL_MTNR"),
    SUPPLIER_BAG_MGMT("ROLE_SUPPLIER_BAG_MGMT"),
    ROLE_DUMMY_SAMPLE("ROLE_DUMMY_SAMPLE"),
    ROLE_SECRET_SAMPLE("ROLE_SECRET_SAMPLE"),
    ROLE_ANY_LOT_QUALITY("ROLE_ANY_LOT_QUALITY"),
    ROLE_VENDOR_SYNC("ROLE_VENDOR_SYNC"),
    ROLE_ADMIN("ROLE_ADMIN"),

    //Prod to fg
    OPERATORPRODUCTION("OPERATOR_PRODUCTION"),
    SUPERVISORPRODUCTION("SUPERVISOR_PRODUCTION"),

    //Aknowledment
    OPERATORWAREHOUSE1("OPERATOR_WAREHOUSE1"),
    SUPERVISORWAREHOUSE1("SUPERVISOR_WAREHOUSE1"),

    //fg to fg
    OPERATORWAREHOUSE2("OPERATOR_WAREHOUSE2"),
    OPERATORWAREHOUSE3("OPERATOR_WAREHOUSE3"),
    OPERATORWAREHOUSE4("OPERATOR_WAREHOUSE4"),
    OPERATORWAREHOUSE5("OPERATOR_WAREHOUSE5"),
    SUPERVISORWAREHOUSE2("SUPERVISOR_WAREHOUSE2"),
    SUPERVISORWAREHOUSE3("SUPERVISOR_WAREHOUSE3"),
    SUPERVISORWAREHOUSE4("SUPERVISOR_WAREHOUSE4"),
    SUPERVISORWAREHOUSE5("SUPERVISOR_WAREHOUSE5"),
    INCOMING_LOTS("ROLE_INCOMMING_LOTS"),
    PILEMANAGEMENT("ROLE_PILEMANAGEMENT"),
    DRYING_INPROGRESS("ROLE_DRYING_INPROGRESS"),
    GINNING_INPROGRESS("ROLE_GINNING_INPROGRESS"),
    DISPATCH("ROLE_DISPATCH"),
    DAYS_LIMIT("ROLE_DAYS_LIMIT"),
    ROLE_DISPATCH_STO("ROLE_DISPATCH_STO"),
    ROLE_STOCK_RECON("ROLE_STOCK_RECON"),
    ROLE_NOTIFICATION_CONFIG("ROLE_NOTIFICATIONS"),

    //History Transactions
    TRANSACTION_HISTORY("ROLE_TRANSACTION_HISTORY"),

    //Picking
    OPERATORPICKING("OPERATOR_PICKING"),
    SUPERVISORPICKING("SUPERVISOR_PICKING"),

    //ALL
    IT_SUPPORT("IT_SUPPORT");


    companion object {
        fun valueOfEnum(value: String): UserRoles? = values().find { it.role == value }
    }
}
