package com.olam.warehouse.vegax.dummyquality.utils

const val DUMMY_QUALITY_CAPTURE = "DUMMY_QUALITY_CAPTURE"
const val DUMMY_QUALITY_CAPTURE_FINISH = "DUMMY_QUALITY_CAPTURE_FINISH"
const val DUMMY_QUALITY_CAPTURE_ACCEPT = "DUMMY_QUALITY_CAPTURE_ACCEPT"
const val DUMMY_QUALITY_LIST = "DUMMY_QUALITY_LIST"
const val DUMMY_QUALITY_VIEW = "DUMMY_QUALITY_VIEW"
const val DUMMY_QUALITY_DATA = "DUMMY_QUALITY_DATA"
const val SUPPLIER_NAME = "SUPPLIER_NAME"
const val SUPPLIER_CODE = "DUMMY_QUALITY_DATA"
const val MATERIAL_NAME = "MATERIAL_NAME"
const val MATERIAL_CODE = "MATERIAL_CODE"
const val MATERIAL_ID = "MATERIAL_ID"
const val QUALITY = "QUALITY"
var IS_VIEW_QUALITY = false
