/**
 * Created by SangiliPandian C on 06-11-2019.
 */
@file:Suppress("detekt.StringLiteralDuplication")

private object LibraryVersion {
    const val KOIN = "4.0.0-RC1"
    const val KOIN_KTOR = "4.0.0-RC1"
    const val KOIN_COMMPOSE = "4.0.0-RC1"
    const val KOIN_VM = "2.1.6"
    const val RETROFIT = "2.6.2"
    const val LOGGING_INTERCEPTOR = "4.12.0"
    const val STETHO = "1.6.0"
    const val TIMBER = "4.7.1"
    const val PLAY_CORE = "1.10.3"
    const val APP_COMPACT = "1.7.0"
    const val RECYCLER_VIEW = "1.0.0"
    const val COORDINATOR_LAYOUT = "1.0.0"
    // 1.1.x version is required in order to support the dark theme functionality in
    // Android Q (adds Theme.MaterialComponents.DayNight)
    const val MATERIAL = "1.9.0"
   // const val MATERIAL = "1.2.0-alpha01"
    const val MATERIAL_DIALOG = "3.1.1"
    const val CONSTRAINT_LAYOUT = "2.0.0-beta3"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT_KTX = "1.1.0"
    const val LIFECYCLE = "1.1.1"
    const val LIFECYCLE_VIEW_MODEL_KTX = "2.6.1"
    const val COIL = "0.9.1"
    const val LOTTIE = "3.0.7"
    const val ROOM = "2.6.1"
    const val WORK = "2.7.0"
    const val VISION = "19.0.0"
    const val LOCATION = "17.0.0"
    const val COMMON = "19.0.0"
    const val GMS_AUTH = "19.0.0"
    const val PERMISSION_DISPATCHER = "4.9.2"
    const val CRASH_ANALYTICS = "2.10.1"
    const val LEAK_CANARY = "2.9.1"
    const val PREFERENCE = "1.1.1"
    const val FLIPTABS = "v1.0"
    const val APPCENTER_SDK = "4.2.0"
    const val MOTOMO_SDK = "4.1.4"
    const val FIREBASE_MSG = "20.1.5"
    const val RANGE_SEEKBAR = "0.3.0"
    const val firebase_config = "19.1.4"
    const val QR_GENERATE = "3.4.0"
    const val CRYPTO = "1.0.0-alpha02"
    const val SAFEROOM = "0.4.4"
    const val SQLCIPHER = "4.5.4"
    const val SQLITE = "2.3.1"
    const val BIOMETRIC = "1.0.1"
    const val MPCHART = "3.1.0"
    const val ARSCENE = "1.15.0"
    const val ARCORE = "1.24.0"
    const val QRCODE = "4.3.0"
    const val PDFVIEWER = "2.8.2"
    const val BOM = "29.0.3"
    const val GLIDE = "4.11.0"
    const val ITEXT = "7.0.4"
    const val ENCRYPTION = "0.0.1"

}

object LibraryDependency {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${CoreVersion.KOTLIN}"
    // Required by Android dynamic feature modules and SafeArgs
    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect:${CoreVersion.KOTLIN}"
    //const val KOIN = "org.koin:koin-android:${LibraryVersion.KOIN}"
    //const val KOIN_VIEWMODEL = "org.koin:koin-androidx-viewmodel:${LibraryVersion.KOIN}"
    const val KOIN = "io.insert-koin:koin-android:${LibraryVersion.KOIN}"
    const val KOIN_CORE = "io.insert-koin:koin-core:${LibraryVersion.KOIN}"
    const val KOIN_COMPAT = "io.insert-koin:koin-android-compat:${LibraryVersion.KOIN}"
    const val KOIN_WORK = "io.insert-koin:koin-androidx-workmanager:${LibraryVersion.KOIN}"
    const val KOIN_KTOR = "io.insert-koin:koin-ktor:${LibraryVersion.KOIN_KTOR}"
    const val KOIN_NAVI = "io.insert-koin:koin-androidx-navigation:${LibraryVersion.KOIN}"
    const val KOIN_COMPOSE = "io.insert-koin:koin-androidx-compose:${LibraryVersion.KOIN_COMMPOSE}"
    const val KOIN_VIEWMODEL = "io.insert-koin:koin-androidx-viewmodel:${LibraryVersion.KOIN}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${LibraryVersion.RETROFIT}"
    const val RETROFIT_GSON_CONVERTER = "com.squareup.retrofit2:converter-gson:${LibraryVersion.RETROFIT}"
    const val LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${LibraryVersion.LOGGING_INTERCEPTOR}"
    const val STETHO = "com.facebook.stetho:stetho:${LibraryVersion.STETHO}"
    const val STETHO_OK_HTTP = "com.facebook.stetho:stetho-okhttp3:${LibraryVersion.STETHO}"
    const val TIMBER = "com.jakewharton.timber:timber:${LibraryVersion.TIMBER}"
    const val SUPPORT_CONSTRAINT_LAYOUT =
        "androidx.constraintlayout:constraintlayout:${LibraryVersion.CONSTRAINT_LAYOUT}"
    const val PLAY_CORE = "com.google.android.play:core:${LibraryVersion.PLAY_CORE}"
    const val APP_COMPACT = "androidx.appcompat:appcompat:${LibraryVersion.APP_COMPACT}"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview:${LibraryVersion.RECYCLER_VIEW}"
    const val COORDINATOR_LAYOUT = "androidx.coordinatorlayout:coordinatorlayout:${LibraryVersion.COORDINATOR_LAYOUT}"
    const val MATERIAL = "com.google.android.material:material:${LibraryVersion.MATERIAL}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${CoreVersion.COROUTINES_ANDROID}"
    const val CORE_KTX = "androidx.core:core-ktx:${LibraryVersion.CORE_KTX}"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${LibraryVersion.FRAGMENT_KTX}"
    const val LIFECYCLE_EXTENSIONS = "android.arch.lifecycle:extensions:${LibraryVersion.LIFECYCLE}"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:${LibraryVersion.LIFECYCLE_VIEW_MODEL_KTX}"
    const val LIVEDATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:${LibraryVersion.LIFECYCLE_VIEW_MODEL_KTX}"
    const val NAVIGATION_FRAGMENT_KTX =
        "androidx.navigation:navigation-fragment-ktx:${CoreVersion.NAVIGATION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${CoreVersion.NAVIGATION}"
    const val COIL = "io.coil-kt:coil:${LibraryVersion.COIL}"
    const val LOTTIE = "com.airbnb.android:lottie:${LibraryVersion.LOTTIE}"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:${LibraryVersion.ROOM}"
    const val ROOM_COMPILER = "androidx.room:room-compiler:${LibraryVersion.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${LibraryVersion.ROOM}"
    const val WORK_RUNTIME = "androidx.work:work-runtime-ktx:${LibraryVersion.WORK}"
    const val MATERIAL_DIALOG =
        "com.afollestad.material-dialogs:core:${LibraryVersion.MATERIAL_DIALOG}"
    const val MATERIAL_INPUT =
        "com.afollestad.material-dialogs:input:${LibraryVersion.MATERIAL_DIALOG}"
    const val VISION = "com.google.android.gms:play-services-vision:${LibraryVersion.VISION}"
    const val LOCATION = "com.google.android.gms:play-services-location:${LibraryVersion.LOCATION}"
    const val COMMON = "com.google.android.gms:play-services-vision-common:${LibraryVersion.COMMON}"
    const val PERMISSION_DISPATCHER =
        "com.github.permissions-dispatcher:permissionsdispatcher:${LibraryVersion.PERMISSION_DISPATCHER}"
    /*const val PERMISSION_DISPATCHER_KTX =
        "com.github.permissions-dispatcher:ktx:${LibraryVersion.PERMISSION_DISPATCHER}"*/
    const val PERMISSION_DISPATCHER_COMPILER =
        "com.github.permissions-dispatcher:permissionsdispatcher-processor:${LibraryVersion.PERMISSION_DISPATCHER}"
    const val CRASH_ANALYTICS =
        "com.crashlytics.sdk.android:crashlytics:${LibraryVersion.CRASH_ANALYTICS}"
    const val LEAK_CANARY =
        "com.squareup.leakcanary:leakcanary-android:${LibraryVersion.LEAK_CANARY}"
    const val PREFERENCE = "androidx.preference:preference-ktx:${LibraryVersion.PREFERENCE}"
    const val FLIPTABS = "com.github.Chrisvin:FlipTabs:${LibraryVersion.FLIPTABS}"
    const val APPCENTER_SDK_ANALYTICS =
        "com.microsoft.appcenter:appcenter-analytics:${LibraryVersion.APPCENTER_SDK}"
    const val APPCENTER_SDK_CRASH =
        "com.microsoft.appcenter:appcenter-crashes:${LibraryVersion.APPCENTER_SDK}"
    const val APPCENTER_SDK_DISTRIBUTE =
        "com.microsoft.appcenter:appcenter-distribute:${LibraryVersion.APPCENTER_SDK}"
    const val MOTOMO_SDK = "com.github.matomo-org:matomo-sdk-android:${LibraryVersion.MOTOMO_SDK}"
    const val FIREBASE_MSG = "com.google.firebase:firebase-messaging:${LibraryVersion.FIREBASE_MSG}"
    const val config = "com.google.firebase:firebase-config:${LibraryVersion.firebase_config}"
    const val RANGE_SEEKBAR =
        "org.florescu.android.rangeseekbar:rangeseekbar-library:${LibraryVersion.RANGE_SEEKBAR}"
    const val QR_GENERATE = "com.google.zxing:core:${LibraryVersion.QR_GENERATE}"
    const val CRYPTO = "androidx.security:security-crypto:${LibraryVersion.CRYPTO}"
    const val SAFEROOM = "com.commonsware.cwac:saferoom.x:${LibraryVersion.SAFEROOM}"
    const val SQLCIPHER = "net.zetetic:android-database-sqlcipher:${LibraryVersion.SQLCIPHER}"
    const val SQLITE = "androidx.sqlite:sqlite:${LibraryVersion.SQLITE}"
    const val BIOMETRIC = "androidx.biometric:biometric:${LibraryVersion.BIOMETRIC}"
    const val MPCHART = "com.github.PhilJay:MPAndroidChart:v${LibraryVersion.MPCHART}"
    const val ARSCENE = "com.google.ar.sceneform.ux:sceneform-ux:${LibraryVersion.ARSCENE}"
    const val ARCORE = "com.google.ar:core:${LibraryVersion.ARCORE}"
    const val GMS_AUTH = "com.google.android.gms:play-services-auth:${LibraryVersion.GMS_AUTH}"
    const val QRCODE = "com.journeyapps:zxing-android-embedded:${LibraryVersion.QRCODE}"
    const val PDFVIEWER = "com.github.barteksc:android-pdf-viewer:${LibraryVersion.PDFVIEWER}"
    const val CRASLYTICS = "com.google.firebase:firebase-crashlytics-ktx"
    const val ANALYTICS = "com.google.firebase:firebase-analytics-ktx"
    const val FIREBASE_BOM = "com.google.firebase:firebase-bom:${LibraryVersion.BOM}"
    const val GLIDE = "com.github.bumptech.glide:glide:${LibraryVersion.GLIDE}"
    const val ITEXT = "com.itextpdf:itext7-core:${LibraryVersion.ITEXT}"
    const val MINTSPRINT_ROOM_ENCRYPTION = "com.mindsprint:room-encryption:${LibraryVersion.ENCRYPTION}"

}
